<h1>Add Post</h1>
<form method="post" action="save">
    <div class="form-group">
        <label for="exampleInputEmail1">Name</label>
        <input type="text" name="name" class="form-control" id="exampleInputEmail1"  >
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Content</label>
        <input type="text" name="ctent" class="form-control" id="exampleInputPassword1"
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">URL_Key</label>
        <input type="text" name="url" class="form-control" id="exampleInputPassword" >
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Tag</label>
        <input type="text" name="tag" class="form-control" id="exampleInputPassword2" >
    </div>
    <br>
    <button type="submit" name="createbtn" class="btn btn-primary">ADD</button>
</form>
