<h1>Edit Post</h1>
<?php $post = $block->getPost();  ?>
<form method="post" action="/blog/post/save">
    <div class="form-group">
        <label for="exampleInputEmail1">Name</label>
        <input type="text" class="form-control" name="name" id="exampleInputEmail1" value="<?php if (isset($post['name'])) echo $post->getName();?>" >
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Content</label>
        <input type="text" class="form-control" name="ctent" id="exampleInputPassword" value="<?php if (isset($post['post_content'])) echo $post->getPostContent();?>" >
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">URL_Key</label>
        <input type="text" class="form-control" name="url" id="exampleInputPassword" value="<?php if (isset($post['url_key'])) echo $post->getUrlKey();?>" >
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Tag</label>
        <input type="text" class="form-control" name="tag" id="exampleInputPassword2" value="<?php if (isset($post['tags'])) echo $post->getTags();?>" >
    </div>
    <br>
    <button type="submit" class="btn btn-primary" name="editbtn" value="<?php echo $post->getPostId()?>">SAVE</button>
</form>
